spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/datajpa
    username: sa
    password:
    driver-class-name: org.h2.Driver

  jpa:
    hibernate:
      ddl-auto: create  #<property name="hibernate.hbm2ddl.auto" value="create" />
    properties:
      #show_sql: true    # <property name="hibernate.show_sql" value="true" /> 아래의 로그를 대신 사용함
      format_sql: true  # <property name="hibernate.format_sql" value="true" />

logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace #쿼리문 파라메타 옵션도 같이 보여줌
